export const dataBill = [
    {
        "id": 1,
        "kyhieumauso": "HD0001",
        "sohoadon": 1,
        "ngaylap": "01/01/2022",
        "thongtinhoadon": "MST người mua: 0108271862 Tên người mua: CÔNG TY CỔ PHẦN TƯ VẤN CÔNG NGHỆ NGS",
        "tongtienchuathue": 36577750,
        "tongtienthue": 0,
        "tongtienchietkhauthuongmai": 0,
        "tongtienphi": "",
        "tongtienthanhtoan": 36577750,
        "donvitiente": "VND",
        "trangthaihoadon": "hoadonmoi",
        "ketquakiemtrahoadon": "Đã cấp mã hóa đơn",
        "hoadonlienquan": "",
        "thongtinlienquan": "",
    },
    {
        "id": 2,
        "kyhieumauso": "HD0001",
        "sohoadon": 2,
        "ngaylap": "01/01/2022",
        "thongtinhoadon": "MST người mua: 0108271862 Tên người mua: CÔNG TY CỔ PHẦN TƯ VẤN CÔNG NGHỆ 3i",
        "tongtienchuathue": 136577750,
        "tongtienthue": 0,
        "tongtienchietkhauthuongmai": 0,
        "tongtienphi": "",
        "tongtienthanhtoan": 136577750,
        "donvitiente": "VND",
        "trangthaihoadon": "hoadonmoi",
        "ketquakiemtrahoadon": "Đã cấp mã hóa đơn",
        "hoadonlienquan": "",
        "thongtinlienquan": "",
    },
    {
        "id": 3,
        "kyhieumauso": "HD0001",
        "sohoadon": 3,
        "ngaylap": "01/01/2022",
        "thongtinhoadon": "MST người mua: 0108271862 Tên người mua: CÔNG TY CỔ PHẦN TƯ VẤN CÔNG NGHỆ Đại Nam",
        "tongtienchuathue": 6577750,
        "tongtienthue": 0,
        "tongtienchietkhauthuongmai": 0,
        "tongtienphi": "",
        "tongtienthanhtoan": 6577750,
        "donvitiente": "VND",
        "trangthaihoadon": "hoadonmoi",
        "ketquakiemtrahoadon": "Đã cấp mã hóa đơn",
        "hoadonlienquan": "",
        "thongtinlienquan": "",
    }
]